name: food_delivery
description: Food Delivery project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  fluttericon: ^2.0.0
  sizer: ^2.0.15
  equatable: ^2.0.3
  flutter_bloc: ^7.3.0
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.6
  firebase_auth: ^3.1.2
  firebase_app_check: ^0.0.3
  replay_cubit:
  cloud_firestore: ^2.5.4
  google_sign_in: ^5.1.1
  google_fonts: ^2.1.0
  formz: ^0.4.0
  get_it: ^7.2.0
  flow_builder: ^0.0.4
  mask_text_input_formatter: ^2.0.0
  clay_containers: ^0.3.2
  image_picker: ^0.8.4+3
  introduction_screen: ^2.1.0
  filter_list: ^1.0.0
  camera: ^0.9.4+3
  rounded_loading_button: ^2.0.8
  lottie: ^1.2.1
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  google_maps_flutter: ^2.1.1
  firebase_messaging: ^11.1.0
  overlay_support: ^1.2.1
  #flutter_neumorphic: ^3.1.0
  #flutter_credit_card: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animated_buttons/
